tesis/tesis/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls')),
    url(r'^', include('events.urls')),
    url(r'^', include('devices.urls')),
]

tesis/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
# Se importan todas las vistas de auth ya que se utilizan la mayoria.
from django.contrib.auth import views as auth_views
# Se importa la funcion unicamente para modificar un atributo de algunas vistas de auth.
from django.urls import reverse_lazy

from . import views
# Se importa el formulario de la autenticacion del usuario modificado.
from .forms import ErrorsHandleAuthenticationForm

app_name='users'
urlpatterns=[
	# Las URLs para loguearse y salir del sistema. Se utilizan las vistas del sistema
	# de autenticacion del django (auth), y en el caso del logueo se modifica el template
	# a utilizar como asi tambien el formulario, ya que se modifica el formulario original.

	url(r'^acceder/$', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=ErrorsHandleAuthenticationForm), name='login'),
	url(r'^salir/$', auth_views.LogoutView.as_view(), name='logout'),

	# Las URLs en caso de querer modificar la contraseña. Se utilizan las vistas y formularios del sistema
	# de autenticacion del django (auth), solo se modifican ciertos atributos.
	
	url(r'^usuarios/cambiar-clave/$', auth_views.PasswordChangeView.as_view(
			template_name='users/password_change_form.html',
			success_url=reverse_lazy('users:password_change_done')),
		name='password_change'),
	url(r'^usuarios/cambiar-clave/exito/$', auth_views.PasswordChangeDoneView.as_view(
			template_name='users/password_change_done.html'),
		name='password_change_done'),

	# Las URLs en caso de haber olvidado la contraseña. Se utilizan las vistas y formularios del sistema
	# de autenticacion del django (auth), solo se modifican ciertos atributos.

	# Se pide ingresar el email para enviar el link de validacion.
	url(r'^acceder/olvide-clave/$', auth_views.PasswordResetView.as_view(
			template_name='users/password_reset_form.html', 
			email_template_name='users/password_reset_email.html', 
			subject_template_name='users/password_reset_subject.txt', 
			success_url=reverse_lazy('users:password_reset_done')), 
		name='password_reset'),
	# Una vez enviado el mail, se notifica de los pasos a seguir.
    url(r'^acceder/olvide-clave/notificado/$', auth_views.PasswordResetDoneView.as_view(
    		template_name='users/password_reset_done.html'), 
    	name='password_reset_done'),
    # Una vez que se accede a la URL enviada por mail, se prosigue a la creacion de una nueva
    # contraseña.
    url(r'^acceder/olvide-clave/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
    		auth_views.PasswordResetConfirmView.as_view(
    			template_name='users/password_reset_confirm.html', 
    			success_url=reverse_lazy('users:password_reset_complete')), 
    		name='password_reset_confirm'),
    # Una vez que se creo la nueva contraseña, se da por concluida la operacion.
    url(r'^acceder/olvide-clave/exito/$', auth_views.PasswordResetCompleteView.as_view(
    		template_name='users/password_reset_complete.html'), 
    	name='password_reset_complete'),

    # URL para en caso de olvidar el usuario, verifica tambien que este activo.
    url(r'^acceder/olvide-usuario/$', views.ForgetUsernameView.as_view(), name='forget_username'),
    # URLS para la creacion de un nuevo usuario, el paso 3 se reutiliza para editar la clave RFID
    # actual de un usuario previamente creado.
	url(r'^usuarios/registro-paso-1/$', views.UserRegisterStep1View.as_view(),
		name='user_register_step_1'),
	url(r'^usuarios/registro-paso-1/$', views.UserRegisterStep1View.as_view(),
		name='user_register_step_1'),
	url(r'^usuarios/registro-paso-2/(?P<pk>[0-9]+)/$', views.UserRegisterStep2View.as_view(),
		name='user_register_step_2'),
	url(r'^usuarios/registro-paso-3/(?P<pk>[0-9]+)/$', views.UserRegisterStep3View.as_view(),
		name='user_register_step_3'),
	url(r'^usuarios/registro-paso-4/(?P<pk>[0-9]+)/$', views.UserRegisterStep4View.as_view(),
		name='user_register_step_4'),
	url(r'^usuarios/registro-paso-5/(?P<pk>[0-9]+)/$', views.UserRegisterStep5View.as_view(),
		name='user_register_step_5'),

	# URLS para dar de baja y alta un usuario.
	url(r'^usuarios/dar-baja/(?P<pk>[0-9]+)-(?P<pk_alt>[0-9]+)/$', views.UserUnsubscribeView.as_view(),
		name='user_unsubscribe'),
	url(r'^usuarios/dar-alta/(?P<pk>[0-9]+)/$', views.UserSubscribeView.as_view(),
		name='user_subscribe'),
	url(r'^usuarios/dar-alta/error/(?P<pk>[0-9]+)-(?P<pk_alt>[0-9]+)/$', views.UserSubscribeErrorView.as_view(),
		name='user_subscribe_error'),

	url(r'^usuarios/editar-codigo/exito/$', views.UserCodeEditSuccessView.as_view(),
		name='user_edit_code_success'),

	# URLS para el manejo de las franjas horarias.
	url(r'^usuarios/franjas-horarias/$', views.TimeZoneListView.as_view(),
		name='time_zone_list'),
	url(r'^usuarios/franjas-horarias/editar/(?P<pk>[0-9]+)/$', views.TimeZoneEditView.as_view(),
		name='time_zone_edit'),
	url(r'^usuarios/franjas-horarias/eliminar/(?P<pk>[0-9]+)/$', views.TimeZoneDeleteView.as_view(),
		name='time_zone_delete'),
	url(r'^usuarios/franjas-horarias/crear/$', views.TimeZoneCreateView.as_view(),
		name='time_zone_create'),

	# URLS para el manejo de categorias.
	url(r'^usuarios/categorias/$', views.CategoryListView.as_view(),
		name='category_list'),
	url(r'^usuarios/categorias/editar/(?P<pk>[0-9]+)/$', views.CategoryEditView.as_view(),
		name='category_edit'),
	url(r'^usuarios/categorias/eliminar/(?P<pk>[0-9]+)/$', views.CategoryDeleteView.as_view(),
		name='category_delete'),
	url(r'^usuarios/categorias/crear/$', views.CategoryCreateView.as_view(),
		name='category_create'),



	url(r'^usuarios/lista/$', views.UsersListView.as_view(), name='users_list'),
	url(r'^usuarios/editar/(?P<pk>[0-9]+)/$', views.UserEditView.as_view(), name='user_edit'),
	url(r'^usuarios/perfil/(?P<pk>[0-9]+)/$', views.UserDetailView.as_view(), name='user_detail'),
	
]

tesis/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from devices.models import Device
from django.http import JsonResponse
# Para sacar (desloguear) un usuario si no pasa el "AdminTest".
from django.contrib.auth import logout
from django.contrib import messages
from django.conf import settings
# Agregados a las vistas para mayor control, como requerimiento de logueo
# y comprobacion de que el usuario sea admin.
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# Para el manejo de mails.
from django.core.mail import send_mail
from django import forms
# Para realizar querysets mas especificos.
from django.db.models import Q
# Para crear el "ModelForm" dado un modelo. Se utiliza para agregar widgets
# en la vista de edicion de las franjas horarias.
from django.forms.models import modelform_factory
# Para renderizar un template rapidamente.
from django.shortcuts import render
# Para redireccionar a una URL.
from django.urls import reverse, reverse_lazy
# Vista generica a la que hay que definir el manejo completo de los pedidos.
from django.views import View
# Vistas genericas para mostrar informacion de los modelos.
from django.views.generic import ListView, TemplateView, DetailView, RedirectView
# Se importan todas las vistas genericas de edicion ya que se utilizan todas ("FormView",
# "CreateView", "UpdateView" y "DeleteView").
from django.views.generic.edit import *
# Para el manejo de las respuestas a los pedidos.
from django.http import HttpResponseRedirect, HttpResponse
# Los formularios de la aplicacion actual ("users").
from .forms import *
# Los modelos de la aplicacion actual ("users").
from .models import *

# Para exportar los usuarios como archivo csv.
import csv
# Para la creacion de la contraseña del usuario.
import random
# Para la comunicacion con el programa principal.
import socket
import requests
import logging
import json
logger = logging.getLogger(__name__)


#----------------------------------------------------------------------------------------
#		Tests para las vistas
#----------------------------------------------------------------------------------------

# Esta vista se encarga de verificar que el usuario este logueado
# como asi tambien que sea staff (admin).
# Es necesario reescribir la funcion test_func, en este caso
# para comprobar que el usuario sea staff.
class AdminTest(LoginRequiredMixin, UserPassesTestMixin):

	def test_func(self):
		test = self.request.user.is_staff
		# Si no es admin el usuario, se lo desloguea.
		if not test:
			logout(self.request)
		return test

#----------------------------------------------------------------------------------------



#----------------------------------------------------------------------------------------
#		Registro de usuario
#----------------------------------------------------------------------------------------

# Esta vista es la utilizada para registrar un nuevo usuario,
# es necesario ser staff (admin) para poder registrar un usuario.
# Se especifica el formulario a utilizar como asi tambien el template.
# Y solo se verifica la validacion del formulario.
class UserRegisterStep1View(AdminTest, CreateView):

	form_class = UserCreationForm
	template_name = 'users/user_register_step_1.html'
	# Este metodo es llamado cuando se realiza un POST con informacion
	# valida, deberia de retornar un HttpResponse.

	def form_valid(self, form):
		# Se ejecuta la funcion "save()" del formulario "UserCreationForm".
		form.save()
		# Se obtiene la clave principal del usuario creado para pasar como
		# argumento ("**kwargs") a la proxima etapa de registro de usuario. 
		pk = form.get_pk()
		return HttpResponseRedirect(reverse('users:user_register_step_2', kwargs={'pk':pk}))


class UserRegisterStep2View(AdminTest, UpdateView):
	model = User
	template_name = 'users/user_register_step_2.html'
	# Este metodo es llamado cuando se realiza un POST con informacion
	# valida, deberia de retornar un HttpResponse.
	form_class = modelform_factory(User,
		fields = [
			'category_list',
			'is_staff',
		],
		widgets={
			'category_list': forms.CheckboxSelectMultiple
		})
	
	# Se obtiene el atributo "is_staff" del usuario creado para en caso
	# de ser "admin" se salta el cuarto paso, esto es debido a que los
	# admin no tienen franjas horarias.
	def get_success_url(self):
		if self.object.is_staff:
			return reverse('users:user_register_step_4', kwargs={'pk':self.kwargs['pk']})
		else:
			return reverse('users:user_register_step_3', kwargs={'pk':self.kwargs['pk']})

# En esta vista se crean las franjas horarias y se especifica la fecha
# limite de la actividad del usuario. Simplemente una vez que se verifica
# que el formulario sea valido, se modifican los campos del usuario con
# los cargados en el formulario.
class UserRegisterStep3View(AdminTest, FormView):

	form_class = UserTimeZoneForm
	template_name = 'users/user_register_step_3.html'

	# Funcion que genera el contexto para el template, en este caso se
	# agrega al contexto todos los objectos del modelo "TimeZone"
	# para poder mostrar informacion acerca de los horarios de las franjas
	# en la pagina.
	def get_context_data(self, **kwargs):
		context = super(UserRegisterStep3View, self).get_context_data(**kwargs)
		context['time_zone'] = TimeZone.objects.all()
		return context

	# Funcion que es llamada una vez que el formulario contenga informacion
	# valida. Se asignan los campos del usuario con el contenido del
	# formulario.
	def form_valid(self, form, **kwargs):
		user = User.objects.get(pk=self.kwargs['pk'])
		user.expiration_date=form.cleaned_data['expiration_date']
		user.monday=form.cleaned_data['monday']
		user.tuesday=form.cleaned_data['tuesday']
		user.wednesday=form.cleaned_data['wednesday']
		user.thursday=form.cleaned_data['thursday']
		user.friday=form.cleaned_data['friday']
		user.saturday=form.cleaned_data['saturday']
		user.sunday=form.cleaned_data['sunday']
		user.save()
		return HttpResponseRedirect(reverse('users:user_register_step_4', kwargs={'pk':self.kwargs['pk']}))


# Vista encargada del manejo del codigo RFID del llavero
class UserRegisterStep4View(AdminTest, FormView):
	# Función que brinda la página una vez que se accede a la URL.
	# Dependiendo de que URL se acceda, carga distinto template.
	form_class = modelform_factory(Device,
		fields = ['device_name'])

	def get(self,request,**kwargs):
		# Se obtiene la URL desde la cual se accedio (URL previa).
		referer = self.request.META.get('HTTP_REFERER')
		# Si se viene del perfil del usuario.
		if 'perfil' in referer:
			context = self.get_context_data(**kwargs)
			return render(request, 'users/user_edit_code.html', context)
		# Si se viene de dar de baja un usuario, recordar que la vista "UserUnsubscribeView"
		# es de tipo "RedirectView", por lo que su "referer" es la pagina desde la cual
		# se accede a dicha vista.
		elif 'registro-paso-4' in referer:
			return HttpResponseRedirect(reverse('users:user_register_step_5', kwargs={'pk':self.kwargs['pk']}))
		# En casos contrarios, como ser que se venga del primer o segundo paso.
		else :
			context = self.get_context_data(**kwargs)
			return render(request, 'users/user_register_step_4.html', context)

	def get_context_data(self, **kwargs):
		user_cat = self.request.user.category_list.all()
		categorias = []
		for cat in user_cat:
			categorias.append(cat.id)
		devices = Device.objects.filter(Q(category_list__in=categorias)).distinct()
		context = {'device_list' : devices}
		return context

	# Funcion encargada de procesar los formularios.
	def post(self,request,**kwargs):
		# Se obtiene la clave principal que se pasa como argumento "**kwargs".
		pk = self.kwargs['pk']
		# Si se presiona el boton "Obtener codigo" u "Obtener otro codigo" en caso de conflicto.
		if 'get_code' in request.POST:
			#Se obtiene el codigo del llavero RFID.
			code = self.get_code(request.POST.get('selected_device'))
			# Se obtiene el usuario activo con el codigo solicitado o None en caso
			# de no existir.
			user = self.get_active_user(code)
			# Se obtiene ademas la variable 'edit' del contexto, la cual existe unicamente
			# si se trata de una edicion de usuario, en caso contrario es "None".
			edit = request.POST.get('edit')
			# Si el codigo obtenido por el metodo "get_code()" es un string vacio, significa
			# que no se capturo algun codigo RFID con el lector, por lo que se muestra una
			# pagina donde da la posibilidad de seguir intentando.
			if code == -1:
				# Se pasa "edit" como contexto para distinguir entre un registro de un
				# nuevo usuario o una edición de uno ya existente.
				context = {'edit':edit}
				device = self.get_context_data(**kwargs)
				context.update(device)
				return render(request, 'users/user_get_code_error.html', context)
			# Si existe el usuario, quiere decir que el llavero RFID ya pertenece a un
			# usuario activo del sistema, por lo se muestra una pagina en la que se brindan
			# tres alternativas: obtener otro codigo (otro llavero), dar de baja al usuario
			# en conflicto (al viejo) u omitir para que el usuario no tenga un codigo RFID,
			# esto significa que el usuario solo puede utilizar el sistema web.
			if user:
				# Se crea el contexto para el template, interesa el nombre completo del
				# usuario en conflicto, su clave en caso de darlo de baja y el codigo para
				# en caso de darlo de baja, guardarlo al usuario.
				# Tambien interesa si es que se esta editando el usuario, es por esto la
				# variable de contexto "edit", que se obtiene del template "user_edit_code.html".
				context = {'user':user.get_full_name(), 'user_pk':user.id, 'user_code':code, 'edit':edit}
				device = self.get_context_data(**kwargs)
				context.update(device)
				return render(request, 'users/user_register_step_4_error.html', context)
			# En caso contrario, se procede a guardar el usuario con el codigo obtenido.
			else:
				# Se guarda el usuario con el codigo obtenido.
				self.set_user_code(pk,code)

tesis/users/templates/users/category_confirm_delete.html
{% extends "base.html" %}

{% block title %}
Categorías
{% endblock title %}

{% block content %}


<!-- Pagina de confirmacion de eliminacion de un turno. -->
<!-- Se acomoda todo el contenido dentro de este contenedor con margenes y un tamaño maximo definido. -->
<div class="container-responsive ml-2 mr-3" style="max-width:600px;">

	<!-- Formulario. -->
    <form class="form-group" method="post">
        {% csrf_token %}
        <!-- Subtitulo. -->
        <h5 class="h5 text-info mb-3">Eliminar categoría:</h5>
        <!-- El formulario de Django se acomoda dentro de esta clase. -->
        <div class="form-group">
        	<!-- Si la categoría a eliminar es valido, o sea que no sea la categoría por defecto. -->
        		<div class="alert alert-warning" role="alert">
        			¿Está seguro que desea eliminar la categoría "{{ object }}"?<br>        		
				</div>
        		<button class="btn btn-outline-secondary" type="submit">Confirmar</button>
        </div>
    </form>
    <!-- Link que permite volver a la pagina anterior. -->
    <a class="text-info" href="/usuarios/categorias">Volver atrás</a>
</div>

{% endblock content %}

tesis/users/templates/users/forget_username_form.html
{% extends "base_login.html" %}

{% block content %}

<!-- Para django-bootstrap4. -->
{% load bootstrap4 %}


<!-- Pagina para recuperar el nombre de usuario mediante DNI. -->
<div class="text-center my-auto">
	<form class="form-signin" method="post">
		{% csrf_token %}
		<h1 class="h3 mb-3">Olvidé mi usuario</h1>
		<div class="alert alert-primary text-left" role="alert">
			Ingrese el DNI para conocer el nombre del usuario.
		</div>
		{% for field in form.visible_fields %}
            <div class="form-group">
                {% bootstrap_field field show_label=False %}
            </div>
        {% endfor %}
        <button class="btn btn-lg btn-primary btn-block mb-2" type="submit">Comprobar</button>
        <div class="text clearfix">
            <a class="float-left" href="/acceder">Volver atrás</a>
        </div>
        <!-- Se incluyen los logos de la facultad y de la universidad. -->
        {% include 'snippets/logos.html' %}
    </form>
</div>

{% endblock content %}

tesis/users/templates/users/password_reset_complete.html
{% extends "base_login.html" %}

{% block content %}


<!-- Pagina de confirmacion de cambio de contraseña. -->
<div class="text-center my-auto">
    <div class="form-signin">
        {% csrf_token %}
        <h1 class="h3 mb-3">Olvidé mi contraseña</h1>
        <div class="alert alert-primary text-left" role="alert">
        	Tu contraseña ha sido establecida. Debería poder <a href="{% url 'users:login' %}" class="alert-link">acceder</a> ahora.
        </div>
        <!-- Se incluyen los logos de la facultad y de la universidad. -->
        {% include 'snippets/logos.html' %}
    </div>
</div>

{% endblock content %}

tesis/users/templates/users/password_reset_confirm.html
{% extends "base_login.html" %}

{% block content %}

<!-- Para django-bootstrap4. -->
{% load bootstrap4 %}


<!-- Pagina accedida mediante el link recibido por el usuario que desea cambiar su contraseña. -->
<div class="text-center my-auto">
    <form class="form-signin" method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3">Olvidé mi contraseña</h1>
        <!-- Si el link es valido. -->
        {% if validlink %}
	        <div class="alert alert-primary text-left" role="alert">
	        	Ingrese su nueva contraseña.
			</div>
			{% for field in form.visible_fields %}
	            <div class="form-group text-left">
	                {% bootstrap_field field show_label=False show_help=False %}
	                <small class="text-muted">{{ field.help_text|safe }}</small>
	            </div>
	        {% endfor %}
	        <button class="btn btn-lg btn-primary btn-block mb-2" type="submit">Siguiente</button>
	    <!-- Si el link ya no es valido (sucede cuando ya se utilizo previamente el link). -->
	    {% else %}
	    	<div class="alert alert-primary text-left" role="alert">
				La dirección URL provista es inválida, posiblemente porque ya fue utilizada.
				Por favor intente recuperar la contraseña nuevamente <a href="{% url 'users:password_reset' %}" class="alert-link">aquí.</a>
			</div>
		{% endif %}
        <!-- Se incluyen los logos de la facultad y de la universidad. -->
        {% include 'snippets/logos.html' %}
    </form>
</div>

{% endblock content %}

tesis/users/templates/users/timezone_create.html
{% extends "base.html" %}

{% block title %}
Franjas horarias
{% endblock title %}

{% block content %}

<!-- Para django-bootstrap4. -->
{% load bootstrap4 %}


<!-- Pagina para crear un nuevo turno. -->
<!-- Se acomoda todo el contenido dentro de este contenedor con margenes y un tamaño maximo definido. -->
<div class="container-responsive ml-2 mr-3" style="max-width:600px;">

    <!-- Formulario. -->
    <form class="form-group" method="post">
        {% csrf_token %}
        <!-- Subtitulo. -->
        <h5 class="h5 text-info mb-3">Crear nuevo turno:</h5>
        <!-- El formulario de Django se acomoda dentro de esta clase. -->
        <div class="form-group mt-5">
        	<!-- Se recorren los campos visibles del formulario. -->
            {% for field in form.visible_fields %}
	            <div class="row">
	                <!-- En pantallas pequeñas ocupa toda la fila, en medianas en adelante solo 4 columnas. -->
	                <div class="col-12 col-sm-4">
	                    <!-- La etiqueta del campo. -->
	                    <div class="form-group">
	                        {{ field.label_tag }}
	                    </div>
	                </div>
	                <!-- En pantallas pequeñas utiliza toda la fila y en medianas en adelante 4 columnas. -->
	                <div class="col-12 col-sm-4">
	                    <!-- Si el formulario contiene errores, los recorre y los muestra. -->
	                    {% if form.non_field_errors %}
	                        <div class="alert alert-danger" role="alert">
	                            {% for error in form.non_field_errors %}
	                                <!-- Se justifica el contenido del texto hacia la izquierda. -->
	                                <div class="text-left">{{ error }}</div>
	                            {% endfor %}
	                        </div>
	                    {% endif %}
	                    <!-- Se recorren los campos visibles del formulario y se los muestran sin la etiqueta, sin texto predefinido (placeholder) y sin ayuda. -->
	                    <div class="form-group">
	                        {% bootstrap_field field show_label=False show_help=False placeholder=False %}
	                        <!-- Se da formato al texto de ayuda del campo. -->
	                        <div style="margin-top: -16px;">
                        		<small class="text-muted">{{ field.help_text }}</small>
                        	</div>
	                    </div>
	                </div>
	            </div>
            {% endfor %}
            </div>
        <button class="btn btn-outline-secondary" type="submit">Crear</button>
    </form>
    <!-- Link que permite volver a la pagina anterior. -->
    <a class="text-info" href="/usuarios/franjas-horarias">Volver atrás</a>
</div>

{% endblock content %}

tesis/users/templates/users/timezone_list.html
{% extends "base.html" %}

{% block title %}
Franjas horarias
{% endblock title %}

{% block content %}


<!-- Pagina que muestra las franjas horarias. -->
<!-- Se acomoda todo el contenido dentro de este contenedor con margenes y un tamaño maximo definido. -->
<div class="container-responsive ml-2 mr-3" style="max-width:600px;">

	<!-- Tabla dentro de la que se coloca la informacion de las franjas. -->
	<!-- Se marca la fila en la que se encuentra el cursor ("table-hover"). -->
	<table class="table table-hover table-responsive">
		<thead>
			<tr>
				<!-- Se especifica un minimo de ancho para la columna para que el titulo no se separe por palabras en caso de achicarse la tabla, por ejemplo en pantallas de celulares. -->
				<th style="min-width:158px;">Nombre del turno</th>
				<th>Desde</th>
				<th>Hasta</th>
				<th>Opciones</th>
			</tr>
		</thead>
		<tbody>
			{% for tz in timezone_list %}
				<tr>
					<td>{{ tz.zone_name }}</td>
					<td>{{ tz.begin }}</td>
					<td>{{ tz.end }}</td>
					<td>
						<!-- Las opciones para cada franja se colocan dentro de un boton de tipo menu desplegable. -->
						<div class="dropleft text-center">
							<button class="btn btn-outline-secondary dropdown-toggle py-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopu="true" aria-expanded="false"></button>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
								<a class="dropdown-item" href="/usuarios/franjas-horarias/editar/{{ tz.id }}">Editar</a>
								<a class="dropdown-item" href="/usuarios/franjas-horarias/eliminar/{{ tz.id }}">Eliminar</a>
							</div>
						</div>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<a class="btn btn-outline-secondary" href="/usuarios/franjas-horarias/crear"><span class="fa fa-plus"></span> Crear nuevo turno</a>
</div>

{% endblock content %}

tesis/users/templates/users/user_edit_code.html
{% extends "base.html" %}

{% block title %}
Cambiar llavero del usuario
{% endblock title %}

{% block content %}

{% block message %}
{% include "common/messages.html" %}
{% endblock message %}

<!-- Para django-bootstrap4. -->
{% load bootstrap4 %}

<!-- Pagina donde se permite cambiar el llavero. -->
<!-- Se acomoda todo el contenido dentro de este contenedor con margenes y un tamaño maximo definido. -->
<div class="container-responsive ml-2 mr-3">

	<!-- Formulario. -->
    <form class="form-group" method="post">
        <div class="container-responsive ml-2 mr-3" style="max-width:600px;">
            <h1 class="h5 text-info mt-2 mb-3">Elija el dispositvo de donde leer el código:</h1>
            <div class="col-12 col-sm-6">
            </div>
            <select class="form-control form-control-sm" name="selected_device">
                {% for device in device_list %}
                <option value={{device.id}}> {{device.device_name}} </option>
                {% endfor %}
            </select>
        </div>

        {% csrf_token %}
        <!-- Se pasa este parametro oculto para indicar que se trata de una edicion y no de un registro de un nuevo usuario. -->
        <input type="hidden" name="edit" value="1">
        <button class="btn btn-outline-secondary m-2" type="submit" name="get_code">
        Obtener nuevo código</button>
        <button class="btn btn-outline-secondary m-2" type="submit" name="delete_code">Eliminar código actual</button>
    </form>
</div>

{% endblock content %}